<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Neomotive.ScanTool.UI</RootNamespace>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.4" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.4" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Neomotive.ScanTool.Core\Neomotive.ScanTool.Core.csproj" />
    <ProjectReference Include="..\..\Shared\Neomotive.UI.Styles\Neomotive.UI.Styles.csproj" />
    <ProjectReference Include="..\..\Shared\Neomotive.Vin\Neomotive.Vin.csproj" />
    <ProjectReference Include="..\..\Shared\Neomotive.Update\Neomotive.Update.csproj" />
  </ItemGroup>
</Project>
