<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Neomotive.Can.Hardware</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Meadow.Linux" Version="3.*-*" />
    <PackageReference Include="Meadow.Foundation.ICs.CAN.Mcp2515" Version="3.*-*" />
  </ItemGroup>
</Project>
